[workspace]
members = ["compiler"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
regex-automata = "0.4.9"
serde = "1.0.219"
serde_json = "1.0.140"
thiserror = "2.0.12"
clap = "4.5.34"
resolver = "2"