[package]
name = "zk-regex-node-frontend"
version = "1.1.0"
license = "MIT"
edition = "2018"
# exclude = ["index.node"]

[lib]
crate-type = ["rlib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zk-regex-compiler = { path = "../compiler", default-features = false }
tabbycat = { version = "0.1", features = ["attributes"], optional = true }
fancy-regex = "0.11.0"
petgraph = "0.6.3"
graph-cycles = "0.1.0"
thiserror = "1.0.40"
serde_json = "1.0.95"
serde = { version = "1.0.159", features = ["derive"] }
itertools = "0.10.3"
clap = { version = "=4.2.1", features = ["derive"] }
ahash = "=0.8.7"
regex-automata = "0.4.5"
regex = "1.10.3"

[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6"]

[features]
default = ["export_neon_main"]
export_neon_main = []
