[package]
name = "timestamp_demo"
type = "bin"
authors = [""]
compiler_version = ">=1.0.0"

[dependencies]
zkregex = { path = "../../noir" }
zkemail = { tag = "v0.4.2", git = "https://github.com/zkemail/zkemail.nr", directory = "lib" }
sha256 = { git = "https://github.com/noir-lang/sha256", tag = "v0.1.3" }
