[package]
name = "x"
type = "bin"
authors = [""]

[dependencies]
regex = { path = "../" }
zkemail = { tag = "v0.4.2", git = "https://github.com/zkemail/zkemail.nr", directory = "lib" }
base64 = { tag = "v0.3.1", git = "https://github.com/noir-lang/noir_base64" }
sha256 = { tag = "v0.1.2", git = "https://github.com/noir-lang/sha256" }
