[package]
name = "compiler"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
regex-automata = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
